const WARM_CHATS_TIPS: readonly string[] = [
  "Leads are hottest in the first 5 minutes.",
  "80% of sales happen after the 5th follow-up.",
  "Most agents stop following up too early.",
  "Consistency beats intensity in lead conversion.",
  "The fortune is in the follow-up.",
  "A fast response builds trust before the first call.",
  "Every missed lead is potential commission lost.",
  "Top agents don't just generate leads - they nurture them.",
  "Automation should create more human conversations, not less.",
  "Your database is your biggest asset.",
  "Most deals come from old leads agents forgot about.",
  "Quick replies increase response rates dramatically.",
  "The best CRM is the one that actually follows up.",
  "More conversations = more appointments.",
  "AI handles the repetitive work so agents can focus on closing.",
  "Most buyers talk to multiple agents - speed matters.",
  "Lead conversion is a timing game.",
  "You don't need more leads if you're losing the ones you already have.",
  "The average lead needs multiple touchpoints before booking.",
  "WarmChats helps agents respond instantly, qualify faster, and book more appointments.",
  "Most inbound leads never get a second follow-up.",
  "The faster the response, the higher the conversion.",
  "Agents lose deals when follow-up becomes inconsistent.",
  "Every unread lead is missed opportunity.",
  "Automation creates consistency at scale.",
  "Most leads don't convert on the first message.",
  "The best sales systems never forget to follow up.",
  "Response time can make or break a deal.",
  "Conversations drive commissions.",
  "The agents who follow up the longest usually win.",
  "A lead ignored today becomes another agent's client tomorrow.",
  "Real estate is a relationship business.",
  "Follow-up is where trust is built.",
  "Most CRMs organize leads. Few convert them.",
  "More speed. More replies. More deals.",
  "Most agents are too busy to follow up perfectly every time.",
  "AI follow-up keeps opportunities alive.",
  "One missed lead can cost thousands in commission.",
  "Lead nurture matters more than lead volume.",
  "The first conversation matters most.",
  "Fast follow-up separates top producers from average agents.",
  "Warm leads turn cold faster than most agents realize.",
  "Great agents stay top of mind.",
  "Every lead deserves immediate attention.",
  "Automation should increase response time, not remove personalization.",
  "The best teams build systems, not just pipelines.",
  "More touchpoints create more trust.",
  "Most buyers choose the agent who responds first.",
  "Consistent follow-up compounds over time.",
  "WarmChats helps agents move faster than the competition.",
];

export const getRandomWarmChatsTip = (): string =>
  WARM_CHATS_TIPS[Math.floor(Math.random() * WARM_CHATS_TIPS.length)];
